### PR TITLE
Fixes to README

### PR DESCRIPTION
**Pull request by ffxsam**
Corrected a mistake regarding type aliases

### CODE REVIEW

**Comment by ffxsam** [comment]
Sorry, I'm not really sure how to edit those files. I don't see any of the text that I changed.

**Comment by gajus** [comment]
Sorry, provided wrong link. This is where the source files are, https://github.com/gajus/eslint-plugin-flowtype/blob/master/.README/README.md

**Comment by ffxsam** [comment]
Are you sure [this](https://github.com/gajus/eslint-plugin-flowtype/blob/master/tests/rules/assertions/typeIdMatch.js) isn't the file I should edit?

Are you saying that editing that will modify the `README.md` file?

**Comment by ffxsam** [comment]
There's nothing in `.README/README.md` that contains the code I had fixed originally.

**Comment by gajus** [comment]
https://github.com/gajus/eslint-plugin-flowtype/tree/master/.README/rules

**Comment by ffxsam** [comment]
Like I said, there's nothing in the rules folder that matches what I changed in my PR.

**Comment by gajus** [comment]
It is https://github.com/gajus/eslint-plugin-flowtype/blob/master/tests/rules/assertions/typeIdMatch.js. You are right. 

After making changes you need to run `npm run readme` to build the docs.

Sorry, I am jumping between several projects.

**Comment by ffxsam** [comment]
Ok, done! I also found a bug in `bin/readmeAssertions.js`. This section in particular was causing `npm run readme` to fail:

https://github.com/gajus/eslint-plugin-flowtype/blob/master/bin/readmeAssertions.js#L33-L36

`require(filePath).default` was `undefined`. Something must've changed with babel, maybe? The valid and invalid codes are exported as defaults, and so they can simply be accessed at the root level (`require(filePath).valid`).

**Comment by gajus** [comment]
Thank you

**Pull request merged**
