### PR TITLE
Added support for flowtype-errors

### PR DESCRIPTION
**Pull request by amilajack**
**⚠️ Do not merge! Work in Progress ⚠️**

Based on https://github.com/gajus/eslint-plugin-flowtype/issues/166

- [x] Add `show-errors` rule to `recommended.json`
- [ ] Manually test locally

### CODE REVIEW

**Comment by amilajack** [comment]
@gajus What are the errors in the most recent tests?

**Comment by gajus** [comment]
> @gajus What are the errors in the most recent tests?

 https://travis-ci.org/gajus/eslint-plugin-flowtype/jobs/187642091#L1418

The errors refer to the commit messages.

It technically should be:

* feat: add flowtype-errors to recommended.json
* fix: make flowtype-errors a direct dependency
* style: remove unnecessary comma

Ideally, please rebase it to a single commit (the first one).

**Comment by amilajack** [comment]
Do you recommend using github's built in squash and merge feature?

**Comment by amilajack** [comment]
Had trouble rebasing. Made a new PR for this:
https://github.com/gajus/eslint-plugin-flowtype/pull/175

**Comment by gajus** [comment]
> Had trouble rebasing. Made a new PR for this:

Sorry, its the festive season and I have had little time to follow up.

It should have been as simple as `git rebase -i HEAD~3`, mark everything for squashing and force push.

**Comment by amilajack** [comment]
I remember trying `git rebase -i HEAD~3` but the git hooks were running tests in between rebasing each commit. The tests were failing so I used `git rebase --continue`. I couldn't seem to figure out what the issue was.

What are your thoughts on the new PR: https://github.com/gajus/eslint-plugin-flowtype/pull/175

**Pull request closed without merging**
