### PR TITLE
Fix #43: Check for a basic flow syntax error; prevents crashing

### LINKED ISSUE #43: Error executing the spaceAfterTypeColon rule
Hi, I had the following error (using the eslint bug report template).
Thanks for your hard work on this plug-in !

**What version of ESLint are you using?**
v3.2.2

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**
```javascript
module.exports = {
    "parser": "babel-eslint",
    "env": {
        "es6": true,
        "node": true
    },
    "plugins": [
        "flowtype",
        "json"
    ],
    "parserOptions": {
        "sourceType": "module"
    },
    "settings": {
        "flowtype": {
            "onlyFilesWithFlowAnnotation": true
        }
    },
    "extends": "eslint:recommended",
    "rules": {
        "block-scoped-var": ["error"],
        "consistent-return": ["error"],
        "curly": ["error"],
        "default-case": ["error"],
        "eqeqeq": ["error"],
        "no-alert": ["error"],
        "no-caller": ["error"],
        "no-div-regex": ["error"],
        "no-eval": ["error"],
        "no-extend-native": ["error"],
        "no-extra-bind": ["error"],
        "no-labels": ["error"],
        "no-floating-decimal": ["error"],
        "no-implicit-globals": ["error"],
        "no-implied-eval": ["error"],
        "no-invalid-this": ["error"],
        "no-lone-blocks": ["error"],
        "no-loop-func": ["error"],
        "no-multi-spaces": ["error"],
        "no-multi-str": ["error"],
        "no-new": ["error"],
        "no-new-func": ["error"],
        "no-new-wrappers": ["error"],
        "no-proto": ["error"],
        "no-iterator": ["error"],
        "no-return-assign": ["error"],
        "no-script-url": ["error"],
        "no-self-compare": ["error"],
        "no-throw-literal": ["error"],
        "no-unmodified-loop-condition": ["error"],
        "no-unused-expressions": ["error"],
        "no-useless-call": ["error"],
        "no-useless-concat": ["error"],
        "no-useless-escape": ["error"],
        "no-void": ["error"],
        "yoda": ["error", "never"],

        "strict": ["error"],

        "no-catch-shadow": ["error"],
        "init-declarations": ["error"],
        "no-label-var": ["error"],
        "no-restricted-globals": ["error"],
        "no-shadow": ["error"],
        "no-shadow-restricted-names": ["error"],
        "no-undef-init": ["error"],
        "no-use-before-define": ["error"],

        "no-process-env": ["error"],
        "no-process-exit": ["error"],

        "array-bracket-spacing": ["error"],
        "brace-style": ["error", "1tbs"],
        "camelcase": ["error"],
        "comma-dangle": ["error"],
        "comma-spacing": ["error"],
        "comma-style": ["error"],
        "computed-property-spacing": ["error"],
        "consistent-this": ["error"],
        "eol-last": ["error"],
        "func-names": ["error", "never"],
        "func-style": ["error", "expression"],
        "indent": ["error", "tab"],
        "jsx-quotes": ["error"],
        "key-spacing": ["error"],
        "keyword-spacing": ["error"],
        "linebreak-style": ["error"],
        "max-depth": ["error", {"max": 5}],
        "max-len": ["error", {"code": 120}],
        "max-params": ["error", {"max": 8}],
        "max-statements-per-line": ["error"],
        "new-cap": ["error"],
        "new-parens": ["error"],
        "no-array-constructor": ["error"],
        "no-lonely-if": ["error"],
        "no-mixed-operators": ["error"],
        "no-nested-ternary": ["error"],
        "no-new-object": ["error"],
        "no-spaced-func": ["error"],
        "no-trailing-spaces": ["error"],
        "no-unneeded-ternary": ["error"],
        "no-whitespace-before-property": ["error"],
        "require-jsdoc": ["error", {
            "require": {
                "FunctionDeclaration": true,
                "MethodDefinition": true,
                "ClassDeclaration": false
            }
        }],
        "valid-jsdoc": ["error", {
            "requireParamDescription": false,
            "requireReturnDescription": false,
            "requireReturn": false
        }],
        "semi": ["error", "always"],
        "semi-spacing": ["error"],
        "space-before-blocks": ["error"],
        "space-before-function-paren": ["error"],
        "space-in-parens": ["error"],
        "space-infix-ops": ["error"],
        "space-unary-ops": ["error"],
        "unicode-bom": ["error"],

        "arrow-spacing": ["error"],
        "no-duplicate-imports": ["error"],
        "no-useless-computed-key": ["error"],
        "no-useless-constructor": ["error"],
        "no-useless-rename": ["error"],
        "no-var": ["error"],
        "prefer-rest-params": ["error"],
        "rest-spread-spacing": ["error"],

        "flowtype/require-parameter-type": ["error"],
        "flowtype/require-return-type": ["error", "always", {"annotateUndefined": "never"}],
        "flowtype/space-after-type-colon": ["error", "always"],
        "flowtype/space-before-type-colon": ["error", "never"],
        "flowtype/type-id-match": ["error", "^([A-Z][a-z0-9]+)+Type$"]
    }
};
```

**What did you do? Please include the actual source code causing the issue.**
Linting the following file:
```javascript
class Foo {
	constructor (context = {} : Object) {

	}
}
```

Via the following command:
```
./node_modules/.bin/eslint <Filename>
```

**What did you expect to happen?**
A message showing me detected errors or parsing errors.

**What actually happened? Please include the actual, raw output from ESLint.**
ESlint crashed.

```
Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at SourceCode.api.getFirstToken (/media/p/blg/api-definition/node_modules/eslint/lib/token-store.js:153:40)
    at /media/p/blg/api-definition/node_modules/eslint-plugin-flowtype/dist/rules/spaceAfterTypeColon.js:26:40
    at arrayEach (/media/p/blg/api-definition/node_modules/lodash/lodash.js:485:11)
    at Function.forEach (/media/p/blg/api-definition/node_modules/lodash/lodash.js:8847:14)
    at EventEmitter.<anonymous> (/media/p/blg/api-definition/node_modules/eslint-plugin-flowtype/dist/rules/spaceAfterTypeColon.js:21:26)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/media/p/blg/api-definition/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/media/p/blg/api-definition/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/media/p/blg/api-definition/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
```

### PR DESCRIPTION
**Pull request by vhf**
See #43.

It definitely works, but I'd understand if creating this rule doesn't fit your vision of the project.

I named it that way so we could add other syntax checks to it should we need to.

### CODE REVIEW

**Comment by gajus** [comment]
Thank you @vhf. @danharper are you happy with the proposal/ implementation?

**Comment by danharper** [comment]
The root cause is a parser issue, but I've been bit by this before recently, so anything that catches those bugs sooner is good 👍

**Comment by gajus** [comment]
@vh happy to merge. However, please amend to PR to comply with the [`CONTRIBUTING`](https://github.com/gajus/eslint-plugin-flowtype/blob/8a96d6a8d73d977a1ed2f68dee748b9a4f06599d/CONTRIBUTING) requirements.

**Comment by vhf** [comment]
Thanks, I will do this later!

**Comment by vhf** [comment]
@gajus Done.

**Comment by gajus** [comment]
Thank you! v2.6.2 published.

**Pull request merged**
