### PR TITLE
Add mixed to no-weak-types

### PR DESCRIPTION
**Pull request by kangax**
Fixes https://github.com/gajus/eslint-plugin-flowtype/issues/361

### CODE REVIEW

**Comment by kangax** [comment]
@gajus my concern is that this is not backward-compatible (from what I can tell) since `mixed` will now be reported unless disabled explicitly.

**Comment by gajus** [comment]
Sorry, I meant as a configuration.

**Comment by kangax** [comment]
@gajus you mean as a separate rule?

**Comment by kangax** [comment]
Hm, not sure I understand. Isn't the rule already accepting a configuration? I just added another option for mixed there.

**Comment by gajus** [comment]
> Hm, not sure I understand. Isn't the rule already accepting a configuration? I just added another option for mixed there.

Sorry. Ignore my comments. :-)

**Pull request merged**
