### PR TITLE
feat: Add `require-read-only-array` rule (#236)

### PR DESCRIPTION
**Pull request by pnevyk**
This rule enforces use of `$ReadOnlyArray` instead of `Array` or array
shorthand notation.

### CODE REVIEW

**Comment by pnevyk** [comment]
Well, right after I submitted this PR I noticed there is already one solving this issue. I am so sorry for this duplicate, it should be probably closed. Next time, I will pay more attention.

**Comment by gajus** [comment]
@pnevyk If you do not mind, I prefer your PR.

**Comment by pnevyk** [comment]
Ok, that's fine. And is there already a decision in points you noted in your PR (name `no-array` and detection of mutation in scope)?

**Comment by gajus** [comment]
> detection of mutation in scope

No need. If user intends to perform a mutation, he will just suppress the warning. Otherwise, it is easy to perform accidental mutation without even being aware of this rule.

As for the rule name, "no-array" is a bit too generic. I think "no-mutable-array" would work the best.

**Comment by pnevyk** [comment]
@gajus So I renamed the rule to `no-mutable-array`. Is there anything to be done yet?

**Comment by gajus** [comment]
Thank you

**Pull request merged**
