### PR TITLE
add an auto-fix option to sortKeys

### PR DESCRIPTION
**Pull request by deecewan**
This adds an option to `--fix` the `sort-keys` rule.

It would be much cleaner using ESLint v4, because multiple tokens can be replaced. However, this is a fairly good (imo) solution, and it tries hard to maintain code style.

edit: ~this currently does not work in a few cases. Namely, `a: (param: number) => void` (or any function type). It also *doesn't* maintain the `?` in `a?: Object`.~

Alright, I think that covers all the use-cases now. If you can think of any more, please let me know.

Fixes: https://github.com/gajus/eslint-plugin-flowtype/issues/212

### CODE REVIEW

**Comment by deecewan** [comment]
@gajus any feedback on this?

**Comment by gajus** [comment]
That was not intentional. For whatever reason Git is not giving me an option revert this PR.

**Comment by gajus** [comment]
I have added to commits that show that this PR does not work with covariant and contravariant properties:

* a439e363654286143bd6966620e8d83dc3c9ea94
* 13670d880fff7bf16c1f0d61b2ca7ee28057766b

Can you pick up the latest code from master and follow up?

**Comment by gajus** [comment]
Furthermore, need to check if nested properties work, e.g.

```js
type FooType = {
  a: number,
  c: {
    a: number,
    c: number,
    b: string,
  },
  b: string,
}

```

**Comment by deecewan** [comment]
I'll take a look in the morning

**Pull request merged**
