### PR TITLE
enforceLineBreak now handles `export type` correctly

### LINKED ISSUE #487: enforce-line-break: issues with auto fixer and `export type`
```
const a = 5;
export type A = string
```

Turns into
```
const a = 5;
export

type A = string;
```

cc: @angelica-bocanegra

### PR DESCRIPTION
**Pull request by Brianzchen**
Closes #487

### CODE REVIEW

**Comment by Brianzchen** [comment]
cc: @gajus @angelica-bocanegra

**Comment by Brianzchen** [comment]
Found that `node.leadingComments` won't work when published, for some reason the test suite still populates the values. And eslint docs recommend `sourceCode.getCommentsBefore()` instead which still lead to reliable tests and now also replicates the real world

https://eslint.org/docs/user-guide/migrating-to-4.0.0#ast-nodes-no-longer-have-comment-properties

**Review by angelica-bocanegra — APPROVED** [review]
LGTM

**Pull request merged**
