### PR TITLE
Add missing keys

### PR DESCRIPTION
**Pull request by StoneCypher**

### CODE REVIEW

**Comment by StoneCypher** [comment]
(i also have no idea why it thinks i changed line 2639, but at least this time it's just one mystery line)

**Comment by gajus** [comment]
This file that you are editing is generated automatically (https://github.com/gajus/eslint-plugin-flowtype/blob/master/CONTRIBUTING.md).

Just run `npm run documentation` to generate a new file.

**Comment by StoneCypher** [comment]
oh.  lawl

apparently `contributing.md` doesn't come up in the web interface anymore.  lovely

**Comment by gajus** [comment]
N/A.

**Pull request closed without merging**
