### PR TITLE
Add fixer to invalid file annotation style message

### PR DESCRIPTION
**Pull request by TrySound**
This helps to make annotation style consistent gradually when touching files.

### CODE REVIEW

**Comment by joanrodriguez** [comment]
👍🏼

**Comment by gajus** [comment]
It appears that this would break `@flow strict`

https://flow.org/en/docs/strict/

**Comment by TrySound** [comment]
@gajus How it will break `@flow strict`? I pass `annotationValue` not hardcoded string. I added test to make it clear.

**Pull request merged**
