### PR TITLE
Support dynamic accessors and callable objects in object-type-delimiter

### PR DESCRIPTION
**Pull request by zertosh**
I could not figure out how to rebuild the documentation, and had to `git commit --no-verify`. I would love to contribute more to this project, but the setup is so complicated and it's not very debug friendly :(

### CODE REVIEW

**Comment by danharper** [comment]
👍 Thanks, I'll update the contributing docs. I agree it's annoying - gets me every time too.

Basically, commit messages have to be prefixed with `fix: ` or `feat: ` or `refactor: ` etc. which determines the version bump automatically.

Makes deployment easier, but dev isn't so nice..

**Comment by danharper** [comment]
Oh, and the docs are built automatically by Travis.

**Comment by zertosh** [comment]
Oh, the problem was with the commit message - so strict :p Just force-pushed a corrected one

**Comment by danharper** [comment]
Thanks, it's deploying now as 2.23.1 :)

**Pull request merged**
