### PR TITLE
docs:Added better installation method to readme

### PR DESCRIPTION
**Pull request by amilajack**
This is probably what most users intend to do

### CODE REVIEW

**Comment by danharper** [comment]
Thanks! Could you prefix the commit message with `docs: `? The CI requires it to make an automated release.

**Comment by gajus** [comment]
@danharper Note that this has been added to `./README.md`, not `./README/README.md`.

**Comment by amilajack** [comment]
@gajus does this change also have to be added to `./README/README.md`?

**Comment by danharper** [comment]
Just the `./README/README.md` file. The root `README.md` is generated by the CI.

**Comment by danharper** [comment]
Fixed & merged as https://github.com/gajus/eslint-plugin-flowtype/commit/b8f8412e2ed7b785f38692a18c5392ecf57e6319 - thanks :)

**Pull request closed without merging**
