### PR TITLE
Feat/do not raise generic spacing on line break

### PR DESCRIPTION
**Pull request by AmauryLiet**

### CODE REVIEW

**Comment by gajus** [comment]
Regarding yarn.lock https://github.com/npm/npm/issues/20603

**Comment by gajus** [comment]
Thank you for the PR.

**Comment by gajus** [comment]
First time I see someone with that name. Caught my attention as my first company was called Anuary.

**Comment by AmauryLiet** [comment]
> Regarding yarn.lock [npm/npm#20603](https://github.com/npm/npm/issues/20603)

I wasn't aware of this issue, it makes a lot of sense actually, thanks ;)

**Comment by AmauryLiet** [comment]
Thanks for the amazingly quick PR handling by the way, it really encourages contributing to the repo

**Pull request merged**
