### PR TITLE
feat: allow line break to satisfy trailing space rule (fixes #31)

### LINKED ISSUE #31: space-after-type-colon should accept newlines
With config,

```
    "flowtype/space-after-type-colon": [2, "always"],
```

Code like this fails,

```
const Fn = ({className}:
  {className?: string}) => {
```

There's no space directly after the colon, but a newline should count to avoid trailing whitespace.

### PR DESCRIPTION
**Pull request by aaron-harvey**
This PR allows a line break to satisfy the trailing space requirement as per issue #31.

### CODE REVIEW

**Comment by danharper** [comment]
Hey sorry, been really busy this week & haven't had chance to look at these PRs - will get to them this weekend! :)

**Comment by nmote** [comment]
Any updates here?

**Comment by danharper** [comment]
Sorry, been busy recently. Should have time free next week.

**Comment by aaron-harvey** [comment]
I corrected the merge conflict that cropped up due to #140

**Comment by danharper** [comment]
Thanks :)

**Pull request merged**
