### PR TITLE
Add no-mixed rule

### PR DESCRIPTION
**Pull request by kangax**
Add no-mixed rule. Follow-up to #362

### CODE REVIEW

**Comment by kangax** [comment]
Currently something off with `yarn check-docs`...

**Comment by gajus** [comment]
You've updated the wrong MD file.

Refer to https://github.com/gajus/eslint-plugin-flowtype/blob/master/CONTRIBUTING.md.

**Comment by gajus** [comment]
Thank you and sorry it took a while to merge this.

**Pull request merged**
