### PR TITLE
feat: add flowtype-errors

### PR DESCRIPTION
**Pull request by amilajack**
@gajus can you test if this works by linking? I'm getting an error saying that `Definition for rule flowtype-errors/show-errors was not found` if i enable `flowtype-errors/show-errors was not found` in my `eslintrc` when using the linked version of this plugin. I haven't worked with a `recommended.json` before I'm not sure how to debug this.

### CODE REVIEW

**Comment by amilajack** [comment]
Accidentally deleted the branch for this 😂

**Comment by danharper** [comment]
I'm unsure about enabling it by default for `recommended`, as I'm sure many people are running `flow` separately anyway. Thoughts @gajus?

**Comment by amilajack** [comment]
> I'm unsure about enabling it by default for recommended,

It is actually disabled in `recommended` config.

**Comment by gajus** [comment]
I am not convinced that adding `eslint-plugin-flowtype-errors` just for the sake of being able to enable it via `flowtype-errors/show-errors` configuration is a valid use case.

To be clear, I am not suggesting to have it enabled by default either. As @danharper said, I too think that most people run separately.

@amilajack I don't see the value of making users to download `eslint-plugin-flowtype-errors` as a dependency of `eslint-plugin-flowtype`. Therefore, I am leaning towards simply documenting the existence of `eslint-plugin-flowtype-errors` in the `README.md`.

If you are Okay with this, please update to restrict changes to the `README.md` file. I am suggesting adding a section "Related projects" after the "Rules" section and documenting your plugin.

**Comment by amilajack** [comment]
Sure thing. I'll close this PR and create a new one for the readme update

**Comment by gajus** [comment]
@danharper I hope thats Okay with you too.

**Pull request closed without merging**
